version: "3"

networks:
  sheleads:

services:
  sla:
    build: .
    ports:
      - "8000:8080"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file: .env
    container_name: sheleads
    networks:
      - sheleads
